# Generated by Django 5.1.3 on 2024-12-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=44)),
                ('category_name_ru', models.CharField(max_length=44, null=True)),
                ('category_name_en', models.CharField(max_length=44, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('user_image', models.ImageField(upload_to='user_image/')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('phone_number', models.IntegerField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze'), ('simple', 'simple')], default='simple', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=34)),
                ('product_name_ru', models.CharField(max_length=34, null=True)),
                ('product_name_en', models.CharField(max_length=34, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('check_original', models.BooleanField(default=True)),
                ('product_video', models.FileField(blank=True, null=True, upload_to='product_videos/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1'), (1, '2'), (1, '3'), (1, '4'), (1, '5')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.userprofile')),
            ],
        ),
    ]
